name: KubeStar CICD

on: push

jobs:
  build-and-push-kubestar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64, linux/amd64]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "manifest"
        run: echo `git log | grep commit | head -1 | cut -d" " -f2` > manifest
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-${{ matrix.platform }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.platform }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.platform }}
      - name: "Build and Push event-exporter Image"
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kubestar/event-exporter
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.platform }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.platform }},mode=max
          tag: "v1.0.5"
